### ISSUE TITLE
Add more Crops 

### ISSUE THREAD

**Issue by 83BitTwitch** [VidhosticeSDK/FS22_DisableCrops#1]
Hello. Its not an issue, but I want to ask. I can add more crops to your code? Like potatos and SugarBeets as they always take over biggest fields on new save game. Thank you for your time 
![Screenshot 2024-03-07 163911](https://github.com/VidhosticeSDK/FS22_DisableCrops/assets/47076028/713b2a76-ab46-49d0-84e4-f6e38c0e1e29)

**Comment by VidhosticeSDK** [comment]
Hi, yes this script can be modified by anyone for their own use. 
I'm not opposed to any modifications, the best would be to add a configuration option directly in the game, but I don't have enough time for that at the moment.

Before name must be "or".
